### ISSUE TITLE
Can't Install this APP 

### ISSUE THREAD

**Issue by BrunoSette** [moxi9/phpfox-amazons3#1]
Can't Install this APP... 

There is not an option to ADD a NEW APP in the v4 version.

**Comment by RaymondBenc** [comment]
The **New App** button is for developer accounts. For premium license holders apps are installed via our Store front at: http://store.phpfox.com/apps?version=4

We will be releasing this app to clients later today so they can install it direct from the AdminCP. I'll leave this case open and update you once it has been released.

**Comment by RaymondBenc** [comment]
S3 app is now out. You can find it at: http://store.phpfox.com/product/787/amazon-s3

To install from your AdminCP to to **Apps > Find More Apps** then paste that URL in the search bar.

If you run into any problems, let us know. Thanks!
